projetodjango/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

# Servir imagens
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [ 
    path('', views.home, name="home"),
    path('category/<int:category_id>/', views.category, name="category"), 
    path('authors/<int:author_id>/', views.authors, name="author"), 
    path('recipes/<int:id>/', views.recipe, name="recipe"), #Ficaria: https://dominio.com.br/recipes/id/
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

class category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

# Recipe = tabelas, parametros = colunas
class Recipe(models.Model):
    title = models.CharField(max_length=35)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=10)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=10)
    preparation_step = models.TextField()
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(
        default=False
    )
    cover = models.ImageField(upload_to='recipe/covers/%Y/%m/%d/') # media/recipe/covers/%Y/%m/%d/ 
    category = models.ForeignKey(
        category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None #None == Null
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default= None
    )

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render

from utils.recipes.factory import make_recipe
from recipes.models import Recipe

def home(request):

    recipes = Recipe.objects.filter(is_published = True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        "recipes": recipes,
    })

def category(request, category_id):
    
    recipes = Recipe.objects.filter(
        category__id=category_id,
        is_published = True,
    )
    contexto = {
        "recipes": recipes,
    }
    return render(request, 'recipes/pages/category.html', contexto)

def authors(request, author_id):
    
    recipes = Recipe.objects.filter(
        author__id=author_id,
        is_published = True,
    )
    contexto = {
        "recipes": recipes,
    }
    return render(request, 'recipes/pages/authors.html', contexto)

def recipe(request, id):

    recipe = Recipe.objects.filter(
        pk=id,
        is_published = True,
    ).order_by('-id').first()
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_datail_page': True,
    })

recipes/templates/recipes/pages/authors.html
{% extends "global/base.html" %}

{% block title %}Authors{% endblock title %}

{% block content %}
    <div class="main-content main-content-list conteiner">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/category.html
{% extends "global/base.html" %}

{% block title %}Categoria {% endblock title %}

{% block content %}
    <div class="main-content main-content-list conteiner">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}

{% block content %}
    <div class="main-content main-content-list conteiner">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends "global/base.html" %}

{% block title %}Bolo de Cenoura{% endblock title %}
{% block content %}
    <div class="main-content main-content-detail conteiner">
        {% include "recipes/partials/recipe.html" %}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="" target="_blank" rel="no-referrer">By André Henrique</a>
    </div>

    <div class="powered">
        <a href="" target="_blank" rel="no-referrer">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css"
    integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css"
    integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css"
    integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="{% static "recipes/css/style.css" %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "recipes:home" %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Receitas</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<!-- Card completo -->
<div class="recipe recipe-list-item">

    <!-- Imagem -->
    <div class="recipe-cover">
        <a href="{% url "recipes:recipe" recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="Temporario">
        </a>
    </div>

    <!-- Titulo -->
    <div class="recipe-title-container">
        <a href="{% url "recipes:recipe" recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>

    <!-- Autor - Data - Categoria -->
    <div class="recipe-author">

        <!-- Autor -->
        <span class="recipe-author-item">
            <a class='recipe-author-link' href="{% url "recipes:author" recipe.author.id %}" >
                <i class="fas fa-user"></i>
                
                    {% if recipe.author.first_name %}
                        {{ recipe.author.first_name }} {{recipe.author.last_name}}
                    {% else %}
                        {{recipe.author.username}} 
                    {% endif %}
            </a>
        </span>

                <!-- Categoria -->
        {% if recipe.category is not None %}

            <span class="recipe-author-item">
                <a href="{% url "recipes:category" recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>

                    <span>{{ recipe.category.name }}</span>
                    
                </a>
            </span>

        {% endif %}

        <!-- Data -->
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>

    </div>

    <!-- Descrição da Receita -->
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <!-- Preparo e Porções -->
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i> Preparo
            </h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-pizza-slice"></i> Porções
            </h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    <!-- Para pagina inicial - Sumir na pagina da Receita -->
    {% if is_datail_page is not True %}
        <footer class="recipe-footer">
            <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                <i class="fas fa-eye"></i>
                <span>Ver mais</span>
            </a>
        </footer>
    {% endif %}

    {% if is_datail_page is True %}
        <div class="preparation_steps">
            {{ recipe.preparation_steps | linebreaksbr}}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>